FIXUP: CHROMIUM: hrtimer: Add a sysctl to lower resolution of timers
0-day errors:

>> kernel/time/hrtimer.c:2166:6: warning: no previous prototype
   for 'hrtimer_smp_call'
>> kernel/time/hrtimer.c:2179:36: error: lvalue required as
   left operand of assignment
>> kernel/time/hrtimer.c:2195:21: error: 'hrtimer_hres_enabled'
   undeclared
>> kernel/time/tick-sched.c:1270:6: warning: no previous prototype
   for 'tick_nohz_switch_to_nohz'

Enable sysctl 'timer_highres' only when CONFIG_HIGH_RES_TIMERS is set.

BUG=b:263289152,b:227610040
TEST=cyclictest --smp -p95 -m with timer_highres=0

Change-Id: I8d19d657503e59c8d25f9c5cba2c4ac63c8beaae
Signed-off-by: Aashish Sharma <shraash@google.com>
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/4570120
Tested-by: Guenter Roeck <groeck@chromium.org>
Reviewed-by: Guenter Roeck <groeck@chromium.org>
Commit-Queue: Guenter Roeck <groeck@chromium.org>