FIXUP: CHROMIUM: Import evdi v1.11.0
0-day reports:

drivers/gpu/drm/evdi/evdi_gem.c: In function 'evdi_gem_vmap':
   drivers/gpu/drm/evdi/evdi_gem.c:318:25: error: implicit declaration of function 'vmap'

Add the missing include file.

BUG=b:235167365
TEST=Connect DisplayLink monitor

Change-Id: I5f609ec06af922d3ff4c595a3f2e4f8ef2273cea
Disallow-Recycled-Builds: test-failures
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/3793183
Reviewed-by: Stephen Boyd <swboyd@chromium.org>
(cherry picked from commit 986eae729e8216f81da1927963658f65f46ec7e9)
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/4639288
Commit-Queue: Aashish Sharma <shraash@google.com>
Auto-Submit: Aashish Sharma <shraash@google.com>
Tested-by: Aashish Sharma <shraash@google.com>