UPSTREAM: drm/i915: fix 64bit divide
ERROR: "__udivdi3" [drivers/gpu/drm/i915/i915.ko] undefined!
ERROR: "__divdi3" [drivers/gpu/drm/i915/i915.ko] undefined!

Store the frequency in kHz and drop 64bit divisions.

v2: Use div64_u64 (Matthew)

v3: store frequency in kHz to avoid 64bit divs (Chris/Ville)

Fixes: dab9178333 ("drm/i915: expose command stream timestamp frequency to userspace")
Reported-by: Matthew Auld <matthew.auld@intel.com>
Signed-off-by: Lionel Landwerlin <lionel.g.landwerlin@intel.com>
Link: https://patchwork.freedesktop.org/patch/msgid/20171113233455.12085-3-lionel.g.landwerlin@intel.com
Reviewed-by: Ewelina Musial <ewelina.musial@intel.com>
Signed-off-by: Ville Syrjälä <ville.syrjala@linux.intel.com>
(cherry picked from commit f577a03ba920df1a9163221d4823627999c59bfd)

BUG=b:274609906
TEST=intel_gpu_top

Change-Id: Ie9d936408175cc4f70cee3a1a16c4d031a2535c2
Signed-off-by: Gareth Yu <gareth.yu@intel.com>
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/4610625
Tested-by: Gareth Yu <gareth.yu@intel.corp-partner.google.com>
Tested-by: Gareth Yu <gareth.yu@gapps.intel.com>
Reviewed-by: Sean Paul <sean@poorly.run>
Commit-Queue: Gareth Yu <gareth.yu@gapps.intel.com>
Reviewed-by: Stéphane Marchesin <marcheu@chromium.org>